function waveStruct = GUI()

    % KlustaMat.GUI()
    % Displays a GUI to walk users through running KlustaMat.
    
    
    [fname, fpath] = uigetfile('*','Select Wave Sources','MultiSelect','on');
    
    names = cellfun(@(x,y) [x y], repmat({fpath},1,4), fname,'UniformOutput',0);
    
    for i = 1:length(names)
        waveStruct.ops(i) = opsFunc(fname(i));
        
    
    end
    
end

function opsFunc(fname)

    width = 650;
    height = 650;
    f = figure('Position', [50, 50, width, height],'Color', 'w');
    
    check_size = [225, 25];
    check_posx = repmat(15, 18, 1);
    check_ind = 1;
    control_height = 600;
    control_width = 250;
    
    %% Feature Options:
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','Energy', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@EnergyCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','Area', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@AreaCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','IdxPeak', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@IdxPeakCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','Peak', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PeakCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','IdxTrough', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@IdxTroughCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','Trough', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@TroughCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','Trough', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@TroughCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','IdxValue', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@IdxValueCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','SpikeWidth', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@IdxValueCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','IdxValue', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@SpikeWidthCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PeakToTrough', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PeakToTroughCallback}, ...
        'Value',1); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','IdxValue', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@IdxValueCallback}, ...
        'Value',0); check_ind = check_ind+1;
    
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA1', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA1Callback}, ...
        'Value',1); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA2', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA2Callback}, ...
        'Value',1); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA3', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA3Callback}, ...
        'Value',1); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    
    %% KlustaMat Options:
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','InstallDir', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@InstallDirCallback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','MinClusters', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@MinClustersCallback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','MaxClusters', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@MaxClustersCallback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    check_objar(check_ind) = uicontrol('Style','checkbox', ...
        'String','PCA4', ...
        'Position',[check_posx(check_ind), control_height-124-25*check_ind, check_size], ...
        'BackgroundColor','w','Callback',{@PCA4Callback}, ...
        'Value',0); check_ind = check_ind+1;
    
    %% PostOp Options:
    
    %%
    hupdate = uicontrol('Style','pushbutton','String','Accept',...
          'Position',[150, control_height-120, 70, 25],...
          'Callback',{@update_Callback}, 'HandleVisibility', 'off');
    
end

function eval(source, eventData)

    update_Callback

end